services:
  backend:
    image: tmoney/accounting
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: always
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - type: bind
        source: ./output
        target: /home/frappe/accounting
      - type: bind
        source: ./assets
        target: /home/frappe/assets
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: tmoney/accounting
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - type: bind
        source: ./output
        target: /home/frappe/accounting
      - type: bind
        source: ./assets
        target: /home/frappe/assets

  create-site:
    image: tmoney/accounting
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - type: bind
        source: ./output
        target: /home/frappe/accounting
      - type: bind
        source: ./assets
        target: /home/frappe/assets
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        wait-for-it -t 120 db:3306;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        if [[ "$create_site" == "yes" ]]; then
         bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app t_money frontend;
        fi;
        if [ -z "$db_backup" ]; then
         echo "No databse to restore";
        else
         bench restore --force --db-root-username=root --db-root-password=admin --admin-password=admin $db_backup;
        fi;
        bench use frontend;
        bench migrate;


  db:
    image: mariadb:11.8
    networks:
      - frappe_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD --protocol=tcp || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
    deploy:
      restart_policy:
        condition: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: tmoney/accounting
    networks:
      - frappe_network
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: always
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - type: bind
        source: ./output
        target: /home/frappe/accounting
      - type: bind
        source: ./assets
        target: /home/frappe/assets
    ports:
      - $port_num:8080

  queue-long:
    image: tmoney/accounting
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: always
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - type: bind
        source: ./output
        target: /home/frappe/accounting
      - type: bind
        source: ./assets
        target: /home/frappe/assets

  queue-short:
    image: tmoney/accounting
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: always
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - type: bind
        source: ./output
        target: /home/frappe/accounting
      - type: bind
        source: ./assets
        target: /home/frappe/assets

  redis-queue:
    image: redis:8.4-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: always
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: always
    volumes:
      - redis-cache-data:/data

  scheduler:
    image: tmoney/accounting
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: always
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - type: bind
        source: ./output
        target: /home/frappe/accounting
      - type: bind
        source: ./assets
        target: /home/frappe/assets

  websocket:
    image: tmoney/accounting
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: always
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - type: bind
        source: ./output
        target: /home/frappe/accounting
      - type: bind
        source: ./assets
        target: /home/frappe/assets

volumes:
  db-data:
  redis-queue-data:
  redis-cache-data:
  sites:
  frontend:
  assets:
  logs:

networks:
  frappe_network:
    driver: bridge
